Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.box_url = "https://vagrantcloud.com/hashicorp/bionic64"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
  config.vm.define "slave1" do |slave1|
    slave1.vm.hostname = "slave1"
  end
  config.vm.define "slave2" do |slave2|
    slave2.vm.hostname = "slave2"
  end
  config.vm.define "slave3" do |slave3|
    slave3.vm.hostname = "slave3"
  end  
  config.vm.provision :shell, path: "bootstrap.sh"
end