Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.box_url = "https://vagrantcloud.com/hashicorp/bionic64"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
  (1..1).each do |i|
    config.vm.define "slave#{i}" do |node|
      node.vm.hostname = "slave#{i}"
    end
  end
  config.vm.provision :shell, path: "bootstrap.sh"
end